name: Matrix with Node.js
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        version: [v14.21.3, v16.20.2, v17.9.1]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}
    - run: npm install https://github.com/indexzero/forever/tarball/v0.5.6
    - name: Running on Platform = ${{ matrix.platform }} Node = ${{ matrix.version }}
      run: npm test
