name: Matrix with Node.js
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        version: [v14.21.3, v16.20.2, v17.9.1]
        npm_version: [v7.7.6,v8.19.4,v8.11.0]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}
    - run: npm install -g npm@${{ matrix.npm_version }}
    - name: Running on Platform = ${{ matrix.platform }} Node = ${{ matrix.version }}
      run: npm test
